// This is a generated file. The source files are in react-dom-bindings/src/server/fizz-instruction-set.
// The build script is at scripts/rollup/generate-inline-fizz-runtime.js.
// Run `yarn generate-inline-fizz-runtime` to generate.
export const markShellTime =
  'requestAnimationFrame(function(){$RT=performance.now()});';
export const clientRenderBoundary =
  '$RX=function(b,c,d,e,f){var a=document.getElementById(b);a&&(b=a.previousSibling,b.data="$!",a=a.dataset,c&&(a.dgst=c),d&&(a.msg=d),e&&(a.stck=e),f&&(a.cstck=f),b._reactRetry&&b._reactRetry())};';
export const completeBoundary =
  '$RB=[];$RV=function(c){$RT=performance.now();for(var a=0;a<c.length;a+=2){var b=c[a],h=c[a+1],e=b.parentNode;if(e){var f=b.previousSibling,g=0;do{if(b&&8===b.nodeType){var d=b.data;if("/$"===d||"/&"===d)if(0===g)break;else g--;else"$"!==d&&"$?"!==d&&"$~"!==d&&"$!"!==d&&"&"!==d||g++}d=b.nextSibling;e.removeChild(b);b=d}while(b);for(;h.firstChild;)e.insertBefore(h.firstChild,b);f.data="$";f._reactRetry&&f._reactRetry()}}c.length=0};$RC=function(c,a){if(a=document.getElementById(a))if(a.parentNode.removeChild(a),c=document.getElementById(c))c.previousSibling.data="$~",$RB.push(c,a),2===$RB.length&&setTimeout($RV.bind(null,$RB),("number"!==typeof $RT?0:$RT)+300-performance.now())};';
export const completeBoundaryUpgradeToViewTransitions =
  '$RV=function(x,e){function m(a,f){var n=a.getAttribute(f);n&&(f=a.style,p.push(a,f.viewTransitionName,f.viewTransitionClass),"auto"!==n&&(f.viewTransitionClass=n),(a=a.getAttribute("vt-name"))||(a="\\u00abT"+H++ +"\\u00bb"),f.viewTransitionName=a,y=!0)}var y=!1,H=0,p=[];try{var g=document.__reactViewTransition;if(g){g.finished.finally($RV.bind(null,e));return}var h=new Map;for(g=1;g<e.length;g+=2)for(var l=e[g].querySelectorAll("[vt-share]"),d=0;d<l.length;d++){var b=l[d];h.set(b.getAttribute("vt-name"),b)}for(l=0;l<e.length;l+=2){var q=e[l],c=q.parentNode;if(c){var k=c.getBoundingClientRect();if(k.left||k.top||k.width||k.height){b=q;for(g=0;b;){if(8===b.nodeType){var t=b.data;if("/$"===t)if(0===g)break;else g--;else"$"!==t&&"$?"!==t&&"$~"!==t&&"$!"!==t||g++}else if(1===b.nodeType){d=b;var z=d.getAttribute("vt-name"),v=h.get(z);m(d,v?"vt-share":"vt-exit");v&&(m(v,"vt-share"),h.set(z,null));var A=d.querySelectorAll("[vt-share]");for(d=0;d<A.length;d++){var B=A[d],C=B.getAttribute("vt-name"),D=h.get(C);\nD&&(m(B,"vt-share"),m(D,"vt-share"),h.set(C,null))}}b=b.nextSibling}for(var u=e[l+1].firstElementChild;u;)null!==h.get(u.getAttribute("vt-name"))&&m(u,"vt-enter"),u=u.nextElementSibling;b=c;do for(var r=b.firstElementChild;r;){var E=r.getAttribute("vt-update");E&&"none"!==E&&!p.includes(r)&&m(r,"vt-update");r=r.nextElementSibling}while((b=b.parentNode)&&1===b.nodeType&&"none"!==b.getAttribute("vt-update"))}}}if(y){h=[];for(q=1;q<e.length;q+=2){var F=e[q].querySelectorAll(\'img[src]:not([loading="lazy"])\');\nc={};for(k=0;k<F.length;c={g:c.g,h:c.h},k++)if(c.g=F[k],"function"===typeof c.g.decode){var G=c.g.decode();c.h=performance.now();console.log("decoding",c.g.src);G.then(function(a){return function(){return console.log("done",a.g.src,performance.now()-a.h)}}(c),function(a){return console.log("error",a)});h.push(G)}}var w=document.__reactViewTransition=document.startViewTransition({update:function(){x(e,document.documentElement.clientHeight);return Promise.race([document.fonts.ready,new Promise(function(a){return setTimeout(a,\n500)})])},types:[]});w.ready.finally(function(){for(var a=p.length-3;0<=a;a-=3){var f=p[a],n=f.style;n.viewTransitionName=p[a+1];n.viewTransitionClass=p[a+1];""===f.getAttribute("style")&&f.removeAttribute("style")}});w.finished.finally(function(){document.__reactViewTransition===w&&(document.__reactViewTransition=null)});$RB=[];return}}catch(a){}x(e)}.bind(null,$RV);';
export const completeBoundaryWithStyles =
  '$RM=new Map;$RR=function(n,w,p){function u(q){this._p=null;q()}for(var r=new Map,t=document,h,b,e=t.querySelectorAll("link[data-precedence],style[data-precedence]"),v=[],k=0;b=e[k++];)"not all"===b.getAttribute("media")?v.push(b):("LINK"===b.tagName&&$RM.set(b.getAttribute("href"),b),r.set(b.dataset.precedence,h=b));e=0;b=[];var l,a;for(k=!0;;){if(k){var f=p[e++];if(!f){k=!1;e=0;continue}var c=!1,m=0;var d=f[m++];if(a=$RM.get(d)){var g=a._p;c=!0}else{a=t.createElement("link");a.href=d;a.rel=\n"stylesheet";for(a.dataset.precedence=l=f[m++];g=f[m++];)a.setAttribute(g,f[m++]);g=a._p=new Promise(function(q,x){a.onload=u.bind(a,q);a.onerror=u.bind(a,x)});$RM.set(d,a)}d=a.getAttribute("media");!g||d&&!matchMedia(d).matches||b.push(g);if(c)continue}else{a=v[e++];if(!a)break;l=a.getAttribute("data-precedence");a.removeAttribute("media")}c=r.get(l)||h;c===h&&(h=a);r.set(l,a);c?c.parentNode.insertBefore(a,c.nextSibling):(c=t.head,c.insertBefore(a,c.firstChild))}if(p=document.getElementById(n))p.previousSibling.data=\n"$~";Promise.all(b).then($RC.bind(null,n,w),$RX.bind(null,n,"CSS failed to load"))};';
export const completeSegment =
  '$RS=function(a,b){a=document.getElementById(a);b=document.getElementById(b);for(a.parentNode.removeChild(a);a.firstChild;)b.parentNode.insertBefore(a.firstChild,b);b.parentNode.removeChild(b)};';
export const formReplaying =
  'addEventListener("submit",function(a){if(!a.defaultPrevented){var c=a.target,d=a.submitter,e=c.action,b=d;if(d){var f=d.getAttribute("formAction");null!=f&&(e=f,b=null)}"javascript:throw new Error(\'React form unexpectedly submitted.\')"===e&&(a.preventDefault(),b?(a=document.createElement("input"),a.name=b.name,a.value=b.value,b.parentNode.insertBefore(a,b),b=new FormData(c),a.parentNode.removeChild(a)):b=new FormData(c),a=c.ownerDocument||c,(a.$$reactFormReplay=a.$$reactFormReplay||[]).push(c,d,b))}});';
